name: Summary

on:
  pull_request:

jobs:

  summary:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate summary
      id: summary
      run: |
        {
        echo 'SUMMARY<<EOF'
        python3 .github/workflows/report.py 
        echo EOF
        } >> "$GITHUB_ENV"

    - name: Notify coverage
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.BURROW_BOT }}
        script: |
          const { SUMMARY } = process.env
          ({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${SUMMARY}`
          })
